# Generated by Django 5.2.6 on 2026-03-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название повода')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=20, verbose_name='Название сбора')),
                ('description', models.TextField(verbose_name='Описание')),
                ('final_sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Необходимая сумма')),
                ('collect_image', models.ImageField(default=None, null=True, upload_to='media')),
                ('completion_datetime', models.DateField(verbose_name='Дата завершения сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='collects.occasion', verbose_name='Повод сбора')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
