---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

services:
  db:
    image: "postgres:18-alpine"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    env_file: ./config/.env
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.2.1-alpine
    expose:
      - "6379"
    networks:
      - web-net

  web:
    <<: &web
      # Image name is changed in production:
      image: "payment-service:dev"
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - "payment-service:dev"
          - "payment-service:latest"
          - "*"
      volumes:
        - django-static:/var/www/django/static
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_started
      networks:
        - web-net
        - postgres-net
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
    command: python -We -bb manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: /bin/sh /code/docker/django/healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery:
    <<: *web
    command: celery -A celery worker -n default@%n -E -Ofair --max-memory-per-child=200000

  flower:
    image: mher/flower:2.0.1
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379
    networks:
      - web-net
    depends_on:
      - redis
      - web


# This task is an example of how to extend existing ones:
#   some_worker:
#     <<: *web
#     command: python manage.py worker_process

networks:
  # Network for postgres, use it for services that need access to the db:
  postgres-net:
  # Network for your internals, use it by default:
  web-net:

volumes:
  postgres-data:
  django-static:
