# Generated by Django 5.2.6 on 2026-03-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, которую собрали')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='collects.collect', verbose_name='Сбор')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='Вкладчик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
